Setting psk.txt permission to 0600
This solves a permission issue which prevents psk.txt from being used by racoon. This has maybe something to do with a newer ipsec/racoon version.

Affected version:
ipsec-tools 0.8.2

Error-log:
ERROR: /etc/racoon/psk.txt has weak file permission
ERROR: failed to open pre_share_key file /etc/racoon/psk.txt